name: Import tasks from YAML to TalentScore
description: Upload your custom MCQ/Essay/CodeGaps tasks to the DevSkiller TalentScore platform
author: DevSkiller
branding:
  icon: upload-cloud
  color: blue

inputs:
  api_key:
    description: "TalentScore API key"
    required: true
  path:
    description: "The path of the yaml file with tasks to import"
    required: true

runs:
  using: docker
  image: Dockerfile