name: go task

on:
  push:
    branches: 
      - master
    
jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: upload and publish task
        uses: ./.github/actions/upload-task
        with:
          api_key: ${{ secrets.DEVSKILLER_API_KEY }}
          id:  fe3217a6-e085-47dd-afff-025be5355d87 
          path: ./gotask