name: go task

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    
jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Devskiller/talentscore-upload-task-action@v1.0.0-alpha.1
        with:
          api_key: ${{ secrets.DEVSKILLER_API_KEY }}
          id:   9f921ba4-df65-46fc-99f7-6cec996299c3  
          path: ./gotask
