name: import task

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    
jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/import-yaml
        with:
          api_key: ${{ secrets.DEVSKILLER_API_KEY_STAGE }}
          path: ./tasks.yml
