name: import task

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    
jobs:
  import-yaml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Devskiller/talentscore-import-yaml-action@v1.0.0
        env:
          PLATFORM_URL: https://api.stage-devskiller.com
        with:
          api_key: ${{ secrets.DEVSKILLER_API_KEY_STAGE }}
          path: ./tasks.yml